Usability improvements

diff --git a/etm b/etm
--- a/etm
+++ b/etm
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -euo pipefail
 
 
 function help {
@@ -29,7 +30,7 @@ function usage {
     echo "   etm info"
     echo "   etm build [--image]"
     echo "   etm run [--image] [--env] [--publish] [--entrypoint] <command>"
-    echo "   etm rcommand [--image] [--env] [--publish] <command>"
+    echo "   etm r [--image] [--env] [--publish] <command>"
     echo "   etm rscript [--image] [--env] [--publish] <path>"
     echo "   etm serve [--image] [--env] [--publish]"
     echo "   etm get-test-set [--image] [--env]"
@@ -42,7 +43,7 @@ function commands {
     echo "Commands:"
     echo "   build                       Build container image"
     echo "   run                         Run containerized command against entrypoint"
-    echo "   rcommand                    Run containerized R command"
+    echo "   r                           Run containerized R command"
     echo "   rscript                     Run containerized R script"
     echo "   serve                       Serve web application"
     echo "   get-test-set                Download test set to ${project_dir}"
@@ -58,7 +59,7 @@ function options {
     echo "   -i --image=<name:tag>       [Not Available] Image [default: ${default_image}]"
     echo "   -p --publish=<host:guest>   [Not Available] Port forward [default: ${default_port_forward}]"
     echo "   -e --env=<key:val>          [Not Available] Environment"
-    echo "   --entrypoint=<path>         [Not Available] Entrypoint [default: ${default_entrypoint}]"
+    echo "   --entrypoint=<str>          [Not Available] Entrypoint [default: ${default_entrypoint}]"
     echo ""
 }
 
@@ -73,15 +74,24 @@ function notes {
 
 
 function examples {
-    #     -------------------------------------------------------------------------------
-    echo "Examples:"
-    echo "   etm build"
-    echo "   [Not Available] etm run --entrypoint sh -c 'echo Hello World!'"
-    echo "   etm rcommand 'print(\"Hello World!\"); print(\"Hello World again!\");'"
-    echo "   etm rscript hello-world.r"
-    echo "   etm serve"
-    echo "   etm get-test-set"
-    echo "   etm info"
+    #        -------------------------------------------------------------------------------
+    echo    "Examples:"
+    echo    "   etm build"
+    echo -e "   etm run bash  \033[33m# Drop into bash shell\033[0m"
+    echo -e "   etm run echo Hello World!  \033[33m# No quotes needed for single line command\033[0m"
+    echo -e "   etm run 'echo Hello World!; echo Hello World again!'  \033[33m# Single quotes needed for multi line command\033[0m"
+    echo -e "   etm run bash hello-world.sh  \033[33m# Specify a program to run a script\033[0m"
+    echo -e "   etm run ./hello-world.sh  \033[33m# Run an executable script containing appropriate shebang\033[0m"
+    echo -e "   etm run R  \033[33m# Drop into R shell\033[0m"
+    echo -e "   etm run \"Rscript -e '1 + 1'\"  \033[33m# Careful consideration of quoting required in this case, rather use convenience command for R\033[0m"
+    echo -e "   etm run Rscript hello-world.r  \033[33m# Specify a program to run a script\033[0m"
+    echo -e "   etm run ./hello-world.r  \033[33m# Run an executable script containing appropriate shebang\033[0m"
+    echo -e "   etm r 1 + 1  \033[33m# Run R single-line command\033[0m"
+    echo -e "   etm r 'print(\"Hello World!\"); print(\"Hello World again!\");'  \033[33m# Run R multi-line command\033[0m"
+    echo -e "   etm rscript hello-world.r  \033[33m# Run a script with Rscript\033[0m"
+    echo    "   etm serve"
+    echo    "   etm get-test-set"
+    echo    "   etm info"
     echo ""
 }
 
@@ -90,25 +100,26 @@ function advanced_examples {
     #     -------------------------------------------------------------------------------
     echo "Advanced Examples:"
     echo "   [Not Available] etm build -i etm-dev:0.01a"
-    echo "   [Not Available] etm run -i etm-dev:0.01a -e name=World --entrypoint sh -c 'echo Hello \${name}!'"
+    echo "   [Not Available] etm run -i etm-dev:0.01a -e name=World --entrypoint 'bash -c' 'echo Hello \${name}!'"
 }
 
 
 function build {
     cd "${repo_dir}/container"
-    podman build -t "${default_image}" .
+    "${container_engine}" build -t "${default_image}" .
 }
 
 
 function run {
-    podman run --rm -it -p "${default_port_forward}" \
+    "${container_engine}" run --rm -it -p "${default_port_forward}" \
         --workdir "${project_dir}" -v "${project_dir}:${project_dir}" \
-        --entrypoint "${default_entrypoint}" "${default_image}" "$@"
+        "${default_image}" ${chosen_entrypoint} "$@"
 }
 
 
 function info {
     echo -e "\033[1mEpitope Matcher Information\033[0m"
+    echo "container_engine: ${container_engine}"
     echo "repo_dir: ${repo_dir}"
     echo "project_dir: ${project_dir}"
     echo "default_image: ${default_image}"
@@ -129,14 +140,31 @@ function resolve_repo {
 }
 
 
+function set_container_engine {
+    # Prefer podman, fall back to docker
+    if ! command -v podman &> /dev/null
+    then
+        if ! command -v docker &> /dev/null
+        then
+            >&2 echo "Error. Requirement not satisfied. Either podman or docker must be installed." 
+            exit 1
+        else
+            echo docker
+        fi
+    else
+        echo podman
+    fi
+}
+
 ## ETM Global variables
+container_engine="${container_engine:-$(set_container_engine)}"
 repo_dir="$(resolve_repo)"
 project_dir="$(pwd)"
 default_image="etm:latest"
 default_host_port=5436
 default_container_port=5436
 default_port_forward="${default_host_port}:${default_container_port}"
-default_entrypoint="Rscript"
+default_entrypoint="sh -c"
 
 case "$1" in
     -h | --help)
@@ -149,16 +177,19 @@ case "$1" in
 
     run)
     shift
+    chosen_entrypoint="${chosen_entrypoint:-${default_entrypoint}}"
     run "$*"
     ;;
 
-    rcommand)
+    r)
     shift
-    run -e "$*"
+    chosen_entrypoint="Rscript -e"
+    run "$*"
     ;;
 
     rscript)
     shift
+    chosen_entrypoint="Rscript"
     run "$*"
     ;;
 
